cloud:
    aws:
        region:
            static: us-east-1
        stack:
            auto: false # disable AWS Cloudformation config gathering

app:
    sns:
        topic: Connell-Portfolio-Topic